# Generated by Django 6.1 on 2026-10-04 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('genre', models.CharField(max_length=60, verbose_name='género')),
                ('platform', models.CharField(max_length=60, verbose_name='plataforma')),
                ('launch_year', models.PositiveIntegerField(verbose_name='año de lanzamiento')),
                ('synopsis', models.TextField(verbose_name='sinopsis')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='portada')),
                ('technical_sheet', models.FileField(blank=True, null=True, upload_to='technical_sheets/', verbose_name='ficha técnica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'videojuego',
                'verbose_name_plural': 'videojuegos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GamerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40, unique=True)),
                ('favorite_genre', models.CharField(blank=True, max_length=60)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil gamer',
                'verbose_name_plural': 'perfiles gamer',
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('jugando', 'Jugando'), ('completado', 'Completado')], default='pendiente', max_length=12)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='puntuación')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='VideoJuegosApp.game')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='VideoJuegosApp.gamerprofile')),
            ],
            options={
                'verbose_name': 'entrada de biblioteca',
                'verbose_name_plural': 'entradas de biblioteca',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('gamer', 'game'), name='unique_game_per_gamer')],
            },
        ),
    ]
