# Generated by Django 6.1 on 2026-10-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoJuegosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='precio'),
        ),
        migrations.AddField(
            model_name='game',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock'),
        ),
    ]
