# Generated by Django 6.1 on 2026-10-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoJuegosApp', '0004_alter_order_options_cart_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='', max_length=150, verbose_name='correo electrónico'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='', max_length=30, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='', max_length=120, verbose_name='nombre completo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito o débito'), ('webpay', 'Webpay')], max_length=20, verbose_name='método de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='estado'),
        ),
    ]
