# Generated by Django 6.1 on 2026-10-05 04:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoJuegosApp', '0005_order_customer_email_order_customer_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='acceso habilitado')),
                ('access_start', models.TimeField(default=datetime.time(8, 0), verbose_name='inicio de acceso')),
                ('access_end', models.TimeField(default=datetime.time(18, 0), verbose_name='término de acceso')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_control', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'control de acceso',
                'verbose_name_plural': 'controles de acceso',
                'ordering': ['user__username'],
            },
        ),
    ]
