# Generated by Django 6.1 on 2026-10-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoJuegosApp', '0006_useraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='unrestricted_hours',
            field=models.BooleanField(default=False, verbose_name='sin restricción horaria'),
        ),
    ]
