"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "unsafe-development-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") # Le dice  a Django qué direcciones web tienen permiso
                                                                          # para mostrar la página.

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'InicioApp',
    'VideoJuegosApp',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'VideoJuegosApp.middleware.AccessScheduleMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Le informamos a Django donde buscar las paginas HTML dentro de la carpeta
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if os.environ.get("DB_ENGINE") == "mysql":      #  ejecutamos la condicion, si estas en tu servidor la computadora detecta 
    # que activaste mysql y se conecta a la base de datos usando las contraseñas del servidor
    DATABASES = {
        "default": {    # Configuramos la BD
            "ENGINE": "django.db.backends.mysql",  # dejamos a mysql como motor base de datos 
            "NAME": os.environ.get("DB_NAME", "gamevault"), # buscamos el entorno de la BD y le asignamos un nombre 
            "USER": os.environ.get("DB_USER", "gamevault_user"), # indica el nombre de usuario para la base de datos 
            "PASSWORD": os.environ.get("DB_PASSWORD", ""), # le indicamos la contraseña de usuario en mysql
            "HOST": os.environ.get("DB_HOST", "127.0.0.1"), # le indicamos donde esta la bd, en este caso la ip del servidor es la del mismo computador que utiliza Django 
            "PORT": os.environ.get("DB_PORT", "3306"), # Asignamos un puerto estandar para mysql 
        }
    }
else:     # Luego condicionamos que si no cumple la condicion 
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3", # django ejecutara SqlLITE 
            "NAME": BASE_DIR / "db.sqlite3", # Y LA INFORMACION SE GUARDARA EN UN ARCHIVO LLAMADO db.sqlite3

        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/' # lE INDICAMOS A LA URL DE DJANGO DONDE UTILIZAR LOS ELEMENTOS DE IMAGEN Y ESTATICOS 

STATIC_ROOT = BASE_DIR / "staticfiles" # Define la carpeta donde Django reunirá los archivos estáticos
MEDIA_URL = "/media/" # Define la URL utilizada para acceder a archivos que suben los usuarios.
MEDIA_ROOT = BASE_DIR / "media" #Indica dónde se guardarán físicamente esos archivos.
LOGIN_URL = "/cuentas/login/"
LOGIN_REDIRECT_URL = "vault_dashboard"
LOGOUT_REDIRECT_URL = "/cuentas/login/"
STATICFILES_DIRS = [ 
    BASE_DIR / 'static',
] # Le informamos a Django donde estan los recursos estaticos



# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
